// <auto-generated />
using System;
using Fitness_Manager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fitness_Manager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251219205720_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Fitness_Manager.Models.Aliment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Calories")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("Glucides")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("Lipides")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("MomentConsommation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("PlanNutritionnelId")
                        .HasColumnType("int");

                    b.Property<string>("Portion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Proteines")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PlanNutritionnelId");

                    b.ToTable("Aliments");
                });

            modelBuilder.Entity("Fitness_Manager.Models.CoachPlanSportif", b =>
                {
                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("PlanSportifId")
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DateAffectation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CoachId", "PlanSportifId");

                    b.HasIndex("PlanSportifId");

                    b.ToTable("CoachPlanSportifs");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Exercice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("DureeSecondes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60);

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Materiel")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("Repetitions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int?>("ReposSecondes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<int?>("SeanceId")
                        .HasColumnType("int");

                    b.Property<int?>("Sets")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.HasKey("Id");

                    b.HasIndex("SeanceId");

                    b.ToTable("Exercices");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("EstLue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Fitness_Manager.Models.PlanNutritionnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaloriesJournalieres")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2000);

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Objectif")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TypeRegime")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PlansNutritionnels");
                });

            modelBuilder.Entity("Fitness_Manager.Models.PlanSportif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("DureeSemaines")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4);

                    b.Property<string>("Niveau")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("PlansSportifs");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Rapport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("Contenu")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CoachId");

                    b.ToTable("Rapports");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Seance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("DureeMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60);

                    b.Property<string>("Jour")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("Ordre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("PlanSportifId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanSportifId");

                    b.ToTable("Seances");
                });

            modelBuilder.Entity("Fitness_Manager.Models.SuiviPoids", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DateMesure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Poids")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("SuiviPoids");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Photo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sexe")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator().HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fitness_Manager.Models.Client", b =>
                {
                    b.HasBaseType("Fitness_Manager.Models.Utilisateur");

                    b.Property<int?>("Age")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateInscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("FrequenceEntrainement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("Objectif")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("PlanNutritionnelId")
                        .HasColumnType("int");

                    b.Property<int?>("PlanSportifId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Poids")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PoidsActuel")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Taille")
                        .HasColumnType("decimal(4,1)");

                    b.HasIndex("CoachId");

                    b.HasIndex("PlanNutritionnelId");

                    b.HasIndex("PlanSportifId");

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Coach", b =>
                {
                    b.HasBaseType("Fitness_Manager.Models.Utilisateur");

                    b.Property<int?>("AnneesExperience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Certifications")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Disponibilites")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Specialite")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("TarifHoraire")
                        .HasColumnType("decimal(8,2)");

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator().HasValue("Coach");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Aliment", b =>
                {
                    b.HasOne("Fitness_Manager.Models.PlanNutritionnel", "PlanNutritionnel")
                        .WithMany("Aliments")
                        .HasForeignKey("PlanNutritionnelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("PlanNutritionnel");
                });

            modelBuilder.Entity("Fitness_Manager.Models.CoachPlanSportif", b =>
                {
                    b.HasOne("Fitness_Manager.Models.Coach", "Coach")
                        .WithMany("CoachPlanSportifs")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Manager.Models.PlanSportif", "PlanSportif")
                        .WithMany("CoachPlanSportifs")
                        .HasForeignKey("PlanSportifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("PlanSportif");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Exercice", b =>
                {
                    b.HasOne("Fitness_Manager.Models.Seance", "Seance")
                        .WithMany("Exercices")
                        .HasForeignKey("SeanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Seance");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Notification", b =>
                {
                    b.HasOne("Fitness_Manager.Models.Client", null)
                        .WithMany("Notifications")
                        .HasForeignKey("ClientId");

                    b.HasOne("Fitness_Manager.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Rapport", b =>
                {
                    b.HasOne("Fitness_Manager.Models.Client", "Client")
                        .WithMany("Rapports")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Manager.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Seance", b =>
                {
                    b.HasOne("Fitness_Manager.Models.PlanSportif", "PlanSportif")
                        .WithMany("Seances")
                        .HasForeignKey("PlanSportifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanSportif");
                });

            modelBuilder.Entity("Fitness_Manager.Models.SuiviPoids", b =>
                {
                    b.HasOne("Fitness_Manager.Models.Client", "Client")
                        .WithMany("SuiviPoids")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Client", b =>
                {
                    b.HasOne("Fitness_Manager.Models.Coach", "Coach")
                        .WithMany("Clients")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fitness_Manager.Models.PlanNutritionnel", "PlanNutritionnel")
                        .WithMany()
                        .HasForeignKey("PlanNutritionnelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fitness_Manager.Models.PlanSportif", "PlanSportif")
                        .WithMany()
                        .HasForeignKey("PlanSportifId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Coach");

                    b.Navigation("PlanNutritionnel");

                    b.Navigation("PlanSportif");
                });

            modelBuilder.Entity("Fitness_Manager.Models.PlanNutritionnel", b =>
                {
                    b.Navigation("Aliments");
                });

            modelBuilder.Entity("Fitness_Manager.Models.PlanSportif", b =>
                {
                    b.Navigation("CoachPlanSportifs");

                    b.Navigation("Seances");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Seance", b =>
                {
                    b.Navigation("Exercices");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Client", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Rapports");

                    b.Navigation("SuiviPoids");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Coach", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("CoachPlanSportifs");
                });
#pragma warning restore 612, 618
        }
    }
}
