// <auto-generated />
using System;
using Fitness_Manager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fitness_Manager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AlimentPlanNutritionnel", b =>
                {
                    b.Property<int>("AlimentsId")
                        .HasColumnType("int");

                    b.Property<int>("PlansNutritionnelsId")
                        .HasColumnType("int");

                    b.HasKey("AlimentsId", "PlansNutritionnelsId");

                    b.HasIndex("PlansNutritionnelsId");

                    b.ToTable("AlimentPlanNutritionnel");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Aliment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Grammage")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Aliments");
                });

            modelBuilder.Entity("Fitness_Manager.Models.CoachPlanSportif", b =>
                {
                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("PlanSportifId")
                        .HasColumnType("int");

                    b.HasKey("CoachId", "PlanSportifId");

                    b.HasIndex("PlanSportifId");

                    b.ToTable("CoachPlanSportifs");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Exercice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Repetitions")
                        .HasColumnType("int");

                    b.Property<int>("SeanceId")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.Property<int>("TempsRepos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeanceId");

                    b.ToTable("Exercices");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Fitness_Manager.Models.PlanNutritionnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaloriesCible")
                        .HasColumnType("int");

                    b.Property<string>("Objectif")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PlansNutritionnels");
                });

            modelBuilder.Entity("Fitness_Manager.Models.PlanSportif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DureeSemaines")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Objectif")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PlansSportifs");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Rapport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chemin_Rapport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Rapports");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Seance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DureeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlanSportifId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanSportifId");

                    b.ToTable("Seances");
                });

            modelBuilder.Entity("Fitness_Manager.Models.SuiviPoids", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Poids")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("SuiviPoids");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator().HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fitness_Manager.Models.Client", b =>
                {
                    b.HasBaseType("Fitness_Manager.Models.Utilisateur");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("PlanNutritionnelId")
                        .HasColumnType("int");

                    b.Property<int>("PlanSportifId")
                        .HasColumnType("int");

                    b.Property<double>("PoidsActuel")
                        .HasColumnType("double");

                    b.Property<double>("Taille")
                        .HasColumnType("double");

                    b.HasIndex("CoachId");

                    b.HasIndex("PlanNutritionnelId");

                    b.HasIndex("PlanSportifId");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Coach", b =>
                {
                    b.HasBaseType("Fitness_Manager.Models.Utilisateur");

                    b.HasDiscriminator().HasValue("Coach");
                });

            modelBuilder.Entity("AlimentPlanNutritionnel", b =>
                {
                    b.HasOne("Fitness_Manager.Models.Aliment", null)
                        .WithMany()
                        .HasForeignKey("AlimentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Manager.Models.PlanNutritionnel", null)
                        .WithMany()
                        .HasForeignKey("PlansNutritionnelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fitness_Manager.Models.CoachPlanSportif", b =>
                {
                    b.HasOne("Fitness_Manager.Models.Coach", "Coach")
                        .WithMany("CoachPlanSportifs")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Manager.Models.PlanSportif", "PlanSportif")
                        .WithMany("CoachPlanSportifs")
                        .HasForeignKey("PlanSportifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("PlanSportif");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Exercice", b =>
                {
                    b.HasOne("Fitness_Manager.Models.Seance", "Seance")
                        .WithMany("Exercices")
                        .HasForeignKey("SeanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seance");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Notification", b =>
                {
                    b.HasOne("Fitness_Manager.Models.Client", "Client")
                        .WithMany("Notifications")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Rapport", b =>
                {
                    b.HasOne("Fitness_Manager.Models.Client", "Client")
                        .WithMany("Rapports")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Seance", b =>
                {
                    b.HasOne("Fitness_Manager.Models.PlanSportif", "PlanSportif")
                        .WithMany("Seances")
                        .HasForeignKey("PlanSportifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanSportif");
                });

            modelBuilder.Entity("Fitness_Manager.Models.SuiviPoids", b =>
                {
                    b.HasOne("Fitness_Manager.Models.Client", "Client")
                        .WithMany("SuiviPoids")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Client", b =>
                {
                    b.HasOne("Fitness_Manager.Models.Coach", "Coach")
                        .WithMany("Clients")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Manager.Models.PlanNutritionnel", "PlanNutritionnel")
                        .WithMany()
                        .HasForeignKey("PlanNutritionnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Manager.Models.PlanSportif", "PlanSportif")
                        .WithMany()
                        .HasForeignKey("PlanSportifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("PlanNutritionnel");

                    b.Navigation("PlanSportif");
                });

            modelBuilder.Entity("Fitness_Manager.Models.PlanSportif", b =>
                {
                    b.Navigation("CoachPlanSportifs");

                    b.Navigation("Seances");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Seance", b =>
                {
                    b.Navigation("Exercices");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Client", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Rapports");

                    b.Navigation("SuiviPoids");
                });

            modelBuilder.Entity("Fitness_Manager.Models.Coach", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("CoachPlanSportifs");
                });
#pragma warning restore 612, 618
        }
    }
}
